development:
  adapter: postgresql
  database: cakes_dev
  username: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: cakes_test
  username: postgres
  pool: 5
  timeout: 5000