development:
  adapter: postgresql
  encoding: unicode
  database: deskboe18ujba
  username: wgjzhnhzmnmkxx
  password: 3cf14f96eab942c6f4cab3a09a8a824022f97aa499235ac7f0216a98f0fea65b
  host: ec2-44-196-174-238.compute-1.amazonaws.com
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: deskboe18ujba
  username: wgjzhnhzmnmkxx
  password: 3cf14f96eab942c6f4cab3a09a8a824022f97aa499235ac7f0216a98f0fea65b
  host: ec2-44-196-174-238.compute-1.amazonaws.com
  port: 5432